### ISSUE TITLE
final todo list for release 1.0.0

### ISSUE THREAD

**Issue by snd** [snd/fragments#3]
- [x] move all the string manipulation and utility functions from forge, fragments, ... into a separate package
  - [x] find a name for the package. candidates: ...
- [x] put the env vars forge into a separate package `fragments-env` that uses the utility package
- [x] make fragments config vars default to env vars
- [x] make listing of available commands in fragments work again by modifying hinoki sources
  - `source.names()` is an optional function that returns all the available names
  - sources returned by `hinoki.source` implement and compose `source.names()`
  - fragments command system uses `source.names()` to list available commands
- [x] `decorateSourceToAlsoLookupWithPrefix(source, 'fragments_')` source decorator in hinoki
- [ ] make `hinoki-trace` work with new `hinoki`
  - [ ] new readme
- [x] `fragments` package
  - [ ] new readme
  - [ ] test readme example
- [x] `fragments-postgres` package
  - [ ] readme
  - [x] migration factories and commands
  - [x] mesa
  - [x] data accessor sources
  - [x] auto table source
- [x] `fragments-user` package
  - [x] adapt to new fragments
- [ ] remove `fragments-forge` repository and package
